name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-          
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.4.1
          arguments: build
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
